import AppShell from "../../components/AppShell";
import { creatorDisplayName } from "../../lib/profileIdentity";
import { getWorkspace, hasAnyRole } from "../../lib/workspace";
import { assignSessionAction, createSession, recordContribution, updateSession } from "./actions";

const first = (value: any) => Array.isArray(value) ? value[0] : value;
const contributionTypes = ["verse", "hook", "songwriting", "harmonies", "lead_vocal", "background_vocals", "production", "recording", "mixing", "mastering", "instrumentation", "creative_direction", "other"];

export default async function SessionsPage() {
  const { admin, project, membership, roles } = await getWorkspace();
  if (!project || !membership) return <AppShell><div className="content empty-state"><h2>Project invitation required</h2></div></AppShell>;
  const [{ data: sessions = [] }, { data: members = [] }, { data: tracks = [] }] = await Promise.all([
    admin.from("studio_sessions").select("*,tracks(id,working_title),session_participants(user_id,profiles(full_name,stage_name)),session_contributions(id,track_id,contribution_type,description,created_at,profiles!session_contributions_contributor_id_fkey(full_name,stage_name),tracks(working_title)),project_tasks(id,title,status,due_date,profiles!project_tasks_assignee_id_fkey(full_name,stage_name))").eq("project_id", project.id).order("starts_at", { ascending: false }),
    admin.from("project_members").select("user_id,profiles(full_name,stage_name)").eq("project_id", project.id).eq("status", "active"),
    admin.from("tracks").select("id,working_title").eq("project_id", project.id).order("working_title"),
  ]);
  const canManage = hasAnyRole(roles, ["Super Admin", "Admin", "Project Lead", "A&R", "Engineer"]);
  const memberOptions = (members || []).map((member: any) => ({ id: member.user_id, name: creatorDisplayName(first(member.profiles)) }));
  return <AppShell><div className="content studio-history-page">
    <div className="heading"><div><span className="eyebrow">PROJECT 001 / STUDIO MEMORY</span><h1>Studio Sessions</h1><p>Schedule the room, reconstruct the backlog and record who actually did what.</p></div></div>
    {canManage && <details className="beat-intake-disclosure"><summary className="beat-intake-summary"><span>SESSION CONTROL</span><strong>Schedule or record a session</strong><small>Use Past session for your media-backed backlog.</small><b>Open +</b></summary><form action={createSession} className="panel operations-form"><label>Session type<select name="is_backlog" defaultValue="false"><option value="false">Upcoming / live session</option><option value="true">Past session / backlog</option></select></label><label>Start<input type="datetime-local" name="starts_at" required /></label><label>End<input type="datetime-local" name="ends_at" /></label><label>Location<input name="location" placeholder="Studio / room" /></label><label>Track<select name="track_id" defaultValue=""><option value="">Project-wide session</option>{(tracks ?? []).map((track: any) => <option key={track.id} value={track.id}>{track.working_title}</option>)}</select></label><label>Participants<select name="participants" multiple>{memberOptions.map((member) => <option key={member.id} value={member.id}>{member.name}</option>)}</select></label><label className="full">Focus / memory notes<textarea name="notes" placeholder="What was planned or what do you remember happening?" /></label><label className="full">Outcome<textarea name="outcomes" placeholder="What came out of the session?" /></label><label className="full">Drive / Dropbox media folder<input type="url" name="media_source_url" placeholder="Paste the folder link containing photos, videos or session audio" /></label><label className="full">Media clues<textarea name="media_notes" placeholder="Who appears, filenames, clips, or anything that helps date and reconstruct the session" /></label><button>Create session record</button></form></details>}
    <div className="session-history-list">{!(sessions ?? []).length && <div className="empty-state"><h2>No sessions recorded</h2><p>Schedule the next session or begin reconstructing the archive.</p></div>}{(sessions ?? []).map((session: any) => { const linkedTrack = first(session.tracks); return <article className="panel session-history-card" key={session.id}>
      <header><div><span className="eyebrow">{session.is_backlog ? "HISTORICAL RECORD" : "STUDIO SESSION"}</span><h2>{linkedTrack?.working_title || "Project-wide session"}</h2><p>{new Date(session.starts_at).toLocaleString("en-KE")} · {session.location || "Location pending"}</p></div><span className={`status-pill ${session.status}`}>{session.status.replaceAll("_", " ")}</span></header>
      <p>{session.notes || "No session notes yet."}</p>{session.outcomes && <blockquote>{session.outcomes}</blockquote>}{session.media_source_url && <a className="secondary-button-inline" target="_blank" rel="noreferrer" href={session.media_source_url}>Open session media folder ↗</a>}
      <div className="session-contribution-list"><span className="eyebrow">RECORDED CONTRIBUTIONS</span>{!(session.session_contributions || []).length && <p>No contributions recorded yet.</p>}{(session.session_contributions || []).map((item: any) => <div key={item.id}><strong>{creatorDisplayName(first(item.profiles))}</strong><span>{item.contribution_type.replaceAll("_", " ")}</span><p>{item.description}</p></div>)}</div>
      <details className="session-inline-tool"><summary>Record what I did +</summary><form action={recordContribution}><input type="hidden" name="session_id" value={session.id} /><label>Contribution<select name="contribution_type">{contributionTypes.map((type) => <option key={type} value={type}>{type.replaceAll("_", " ")}</option>)}</select></label><label>Track<select name="track_id" defaultValue={session.track_id || ""}><option value="">Project-wide</option>{(tracks ?? []).map((track: any) => <option key={track.id} value={track.id}>{track.working_title}</option>)}</select></label><textarea name="description" required placeholder="e.g. Laid Verse 2, helped write the hook, arranged harmonies…" /><button>Record contribution</button></form></details>
      <details className="session-inline-tool"><summary>Assign follow-up work +</summary><form action={assignSessionAction}><input type="hidden" name="session_id" value={session.id} /><label>Assign to<select name="assignee_id" required defaultValue=""><option value="" disabled>Choose project member</option>{memberOptions.map((member) => <option key={member.id} value={member.id}>{member.name}</option>)}</select></label><label>Track<select name="track_id" defaultValue={session.track_id || ""}><option value="">Project-wide</option>{(tracks ?? []).map((track: any) => <option key={track.id} value={track.id}>{track.working_title}</option>)}</select></label><input name="title" required placeholder="e.g. Harmonize the hook" /><textarea name="description" placeholder="Add the exact note or direction" /><input type="date" name="due_date" /><button>Assign action</button></form></details>
      {!!session.project_tasks?.length && <div className="session-task-list">{session.project_tasks.map((task: any) => <div key={task.id}><strong>{task.title}</strong><span>{creatorDisplayName(first(task.profiles))} · {task.status.replaceAll("_", " ")}</span></div>)}</div>}
      {canManage && <details className="session-inline-tool"><summary>Manage session +</summary><form action={updateSession}><input type="hidden" name="session_id" value={session.id} /><select name="status" defaultValue={session.status}><option value="scheduled">Scheduled</option><option value="in_session">In Session</option><option value="follow_up_required">Follow-Up Required</option><option value="complete">Complete</option><option value="cancelled">Cancelled</option></select><input name="outcomes" placeholder="Outcome / follow-up" defaultValue={session.outcomes || ""} /><input type="url" name="media_source_url" defaultValue={session.media_source_url || ""} placeholder="Drive / Dropbox folder" /><textarea name="media_notes" defaultValue={session.media_notes || ""} placeholder="Media notes" /><button>Update session</button></form></details>}
    </article>; })}</div>
  </div></AppShell>;
}
