import type { Metadata } from "next";
import Link from "next/link";
import PublicNavigation from "../../components/PublicNavigation";
import PublicFooter from "../../components/PublicFooter";
import { ArrowUpRight } from "../../components/Icons";

export const metadata: Metadata = { title:"About",description:"Why FACKTS Music is building operating infrastructure for African creative work.",alternates:{canonical:"/about"} };

const principles=[
  ["Built from listening","Years of artist interviews, creator profiles, EPK work, industry conversations and real projects revealed the same operational gaps."],
  ["Built with the room","Artists, producers, engineers, A&R and Project Leads need different views of one shared creative truth."],
  ["Built through practice","Project 001 is not a fictional demo. It is the founding real-world implementation shaping what the platform becomes."],
];
export default function AboutPage(){return <main className="public-site"><PublicNavigation/><header className="public-page-hero about"><span className="public-eyebrow">ABOUT FACKTS MUSIC</span><h1>Creative work deserves<br/><em>operating infrastructure.</em></h1><p>FACKTS Music is a FACKTS Africa platform built to help music ventures organise people, ideas, sessions, decisions and creative history without losing the energy of the work.</p></header><section className="public-story-grid"><div><span className="public-eyebrow">THE PROBLEM</span><h2>The music moves.<br/>The record disappears.</h2></div><div className="public-story-copy"><p>Creative teams already know how to make extraordinary work. The difficulty is everything surrounding it: beats scattered in chats, unclear assignments, missed sessions, forgotten contributions and decisions that live only in somebody’s memory.</p><p>FACKTS Music creates one living project record so everyone can see what is moving, what needs attention and what has been built together.</p></div></section><section className="public-principles"><div className="public-section-heading"><div><span className="public-eyebrow">HOW WE BUILD</span><h2>Listen. Operate. Learn. Repeat.</h2></div></div><div>{principles.map(([title,copy],index)=><article key={title}><span>{String(index+1).padStart(2,"0")}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section><section className="public-origin-section"><div className="public-origin-mark">001</div><div><span className="public-eyebrow">THE FOUNDING IMPLEMENTATION</span><h2>Project 001 is the laboratory.</h2><p>It gives the platform a real environment: working artists, beats, claims, sessions, tasks, project roles and actual operating decisions. Every useful feature must answer a real need before it becomes part of the system.</p><p>From there, FACKTS Music can grow carefully into infrastructure for studios, labels, collectives and creative ventures across Africa.</p></div></section><section className="public-page-cta"><span className="public-eyebrow">ENTER THE ROOM</span><h2>Ready to build with a clearer creative record?</h2><div><Link href="/signup" className="public-button public-button-primary">Create Account <ArrowUpRight size={16}/></Link><Link href="/partner" className="public-button public-button-ghost">Partner With Us <ArrowUpRight size={16}/></Link></div></section><PublicFooter/></main>}
