import { notFound } from "next/navigation";
import PublicNavigation from "../../../components/PublicNavigation";
import PublicFooter from "../../../components/PublicFooter";
import { creatorDisplayName } from "../../../lib/profileIdentity";
import { createAdminClient } from "../../../lib/supabase/admin";

const first = (value: any) => Array.isArray(value) ? value[0] : value;
function mediaEmbed(url?: string | null, music = false) { if(!url)return null; try{const p=new URL(url),h=p.hostname.replace(/^www\./,"").toLowerCase();if(h==="youtu.be")return`https://www.youtube.com/embed/${p.pathname.slice(1).split("/")[0]}`;if(h.includes("youtube.com"))return`https://www.youtube.com/embed/${p.searchParams.get("v")||p.pathname.split("/").filter(Boolean).pop()}`;if(h.includes("vimeo.com"))return`https://player.vimeo.com/video/${p.pathname.split("/").filter(Boolean).pop()}`;if(music&&h.includes("spotify.com"))return`https://open.spotify.com/embed${p.pathname}`;if(music&&h.includes("music.apple.com"))return`https://embed.music.apple.com${p.pathname}${p.search}`;if(music&&h.includes("soundcloud.com"))return`https://w.soundcloud.com/player/?url=${encodeURIComponent(url)}&color=%23f5a623&auto_play=false&hide_related=true&show_comments=false`;}catch{}return null;}

export default async function PublicCreatorPage({params}:{params:Promise<{userId:string}>}) {
 const {userId:handle}=await params,admin=createAdminClient();
 const fields="id,stage_name,nickname,avatar_url,hero_image_url,bio,epk_tagline,location,skills_genres,social_links,streaming_links,top_songs,photo_catalog,interview_title,interview_url,achievements,creator_types,profile_visibility,public_slug";
 let {data:profile}=await admin.from("profiles").select(fields).eq("public_slug",handle).eq("profile_visibility","public").maybeSingle();
 if(!profile&&/^[0-9a-f-]{36}$/i.test(handle))({data:profile}=await admin.from("profiles").select(fields).eq("id",handle).eq("profile_visibility","public").maybeSingle());
 if(!profile)notFound();
 const {data:credits=[]}=await admin.from("track_contributors").select("id,contribution_role,tracks(working_title)").eq("user_id",profile.id).eq("approved",true);
 const name=creatorDisplayName(profile),photos=(profile.photo_catalog||[]).slice(0,5),interview=mediaEmbed(profile.interview_url);
 return <><PublicNavigation/><main className="public-creator-shell"><div className="content creator-profile-page public-creator-page">
  <section className={`creator-profile-hero${profile.hero_image_url?" has-hero-image":""}`} style={profile.hero_image_url?{backgroundImage:`linear-gradient(90deg,rgba(2,7,13,.97),rgba(2,7,13,.68),rgba(2,7,13,.22)),url("${profile.hero_image_url}")`}:undefined}><div className="creator-profile-avatar">{profile.avatar_url?<img src={profile.avatar_url} alt={name}/>:name.slice(0,2).toUpperCase()}</div><div><span className="eyebrow">FACKTS MUSIC CREATOR</span><h1>{name}</h1><p>{profile.epk_tagline||profile.bio||"Independent creator on FACKTS Music."}</p><div className="person-roles-wrap">{(profile.creator_types||[]).map((type:string)=><span className="role-chip" key={type}>{type}</span>)}</div></div></section>
  {!!photos.length&&<section className="creator-photo-catalog"><div className="creator-section-heading"><span className="eyebrow">MEDIA</span><h2>Photo catalogue</h2></div><div>{photos.map((photo:string,index:number)=><img src={photo} alt={`${name} ${index+1}`} key={photo}/>)}</div></section>}
  <section className="creator-profile-grid compact"><article className="panel"><span className="eyebrow">PROFILE</span><h2>Creative identity</h2><p>{profile.bio||"Bio coming soon."}</p><dl><div><dt>Location</dt><dd>{profile.location||"Not listed"}</dd></div><div><dt>Sound</dt><dd>{(profile.skills_genres||[]).join(" · ")||"Not listed"}</dd></div></dl><div className="public-profile-links">{profile.social_links?.primary&&<a href={profile.social_links.primary} target="_blank" rel="noreferrer">Social ↗</a>}{profile.streaming_links?.primary&&<a href={profile.streaming_links.primary} target="_blank" rel="noreferrer">Streaming ↗</a>}</div></article><article className="panel creator-top-five"><span className="eyebrow">TOP FIVE</span><h2>Selected music</h2><div className="creator-song-list">{!(profile.top_songs||[]).length&&<p>No selected songs yet.</p>}{(profile.top_songs||[]).map((song:any,index:number)=>{const src=mediaEmbed(song.url,true);return <div className="creator-song-player" key={`${song.title}-${index}`}><div className="creator-song-heading"><span>{String(index+1).padStart(2,"0")}</span><strong>{song.title}</strong>{song.url&&<a href={song.url} target="_blank" rel="noreferrer">Open ↗</a>}</div>{src?<iframe src={src} title={`${song.title} player`} loading="lazy" allow="autoplay; encrypted-media; picture-in-picture"/>:song.url&&<a className="creator-song-fallback" href={song.url} target="_blank" rel="noreferrer">Play on original platform ↗</a>}</div>})}</div></article></section>
  {(profile.interview_url||profile.interview_title)&&<section className="panel creator-interview compact"><div><span className="eyebrow">FEATURED INTERVIEW</span><h2>{profile.interview_title||`Meet ${name}`}</h2></div>{interview?<iframe src={interview} title={profile.interview_title||`${name} interview`} allow="accelerometer; autoplay; encrypted-media; picture-in-picture" allowFullScreen/>:<a className="secondary-button-inline" href={profile.interview_url} target="_blank" rel="noreferrer">Watch interview ↗</a>}</section>}
  <section className="panel compact-public-credits"><div className="creator-panel-heading"><div><span className="eyebrow">APPROVED CREDITS</span><h2>Music history</h2></div><span>{(credits??[]).length} records</span></div><div className="creator-credit-list">{(credits??[]).map((credit:any,index:number)=><div className="creator-credit-row premium" key={credit.id}><span className="creator-credit-index">{String(index+1).padStart(2,"0")}</span><strong>{first(credit.tracks)?.working_title||"Untitled track"}</strong><span>{String(credit.contribution_role).replaceAll("_"," ")}</span><b>Approved</b></div>)}</div><p className="public-credit-privacy">Credits are visible; project files and internal records remain private.</p></section>
  {!!profile.achievements?.length&&<section className="panel creator-achievements compact"><span className="eyebrow">HIGHLIGHTS</span><h2>Achievements</h2><ul>{profile.achievements.map((item:string)=><li key={item}>{item}</li>)}</ul></section>}
 </div></main><PublicFooter/></>;
}
