"use server";

import {revalidatePath} from "next/cache";
import {requireControlRoomAdmin} from "../../../lib/controlRoom";
import {createAdminClient} from "../../../lib/supabase/admin";

const read=(fd:FormData,key:string)=>String(fd.get(key)||"").trim();

export async function updateManagedProject(fd:FormData){const user=await requireControlRoomAdmin();const admin=createAdminClient();const projectId=read(fd,"project_id");const status=read(fd,"status");const capacity=Number(read(fd,"default_beat_capacity"));if(!["active","paused","completed","archived"].includes(status))throw new Error("Invalid project status.");if(!Number.isInteger(capacity)||capacity<1||capacity>12)throw new Error("Artist capacity must be between 1 and 12.");const {error}=await admin.from("projects").update({status,default_beat_capacity:capacity,updated_at:new Date().toISOString()}).eq("id",projectId);if(error)throw new Error(error.message);await admin.from("platform_events").insert({user_id:user.id,project_id:projectId,event_name:"project_settings_updated",category:"admin",entity_type:"project",entity_id:projectId});revalidatePath("/admin/projects");revalidatePath("/admin");}

export async function updateSystemSetting(fd:FormData){const user=await requireControlRoomAdmin();const admin=createAdminClient();const key=read(fd,"setting_key");const raw=read(fd,"setting_value");let value:any;try{value=JSON.parse(raw)}catch{throw new Error("Setting value must be valid JSON.")}const {error}=await admin.from("system_settings").upsert({setting_key:key,setting_value:value,updated_by:user.id,updated_at:new Date().toISOString()},{onConflict:"setting_key"});if(error)throw new Error(error.message);await admin.from("platform_events").insert({user_id:user.id,event_name:"system_setting_updated",category:"admin",metadata:{setting_key:key}});revalidatePath("/admin/system");}

export async function addUsersToManagedProject(fd:FormData){const actor=await requireControlRoomAdmin();const admin=createAdminClient();const projectId=read(fd,"project_id");const roleName=read(fd,"role_name");const userIds=fd.getAll("user_ids").map(String).filter(Boolean);if(!userIds.length)throw new Error("Select at least one user.");const {data:role}=await admin.from("roles").select("id").eq("name",roleName).maybeSingle();if(!role)throw new Error("Choose a valid project role.");for(const userId of userIds){const {data:existing}=await admin.from("project_members").select("id,status").eq("project_id",projectId).eq("user_id",userId).maybeSingle();let memberId=existing?.id;if(memberId)await admin.from("project_members").update({status:"active"}).eq("id",memberId);else{const created=await admin.from("project_members").insert({project_id:projectId,user_id:userId,status:"active"}).select("id").single();if(created.error)throw new Error(created.error.message);memberId=created.data.id;}await admin.from("member_roles").upsert({project_member_id:memberId,role_id:role.id},{onConflict:"project_member_id,role_id"});await admin.from("notifications").insert({user_id:userId,project_id:projectId,type:"project_added",title:"You were added to a project",body:`You now have ${roleName} access.`});await admin.from("platform_events").insert({user_id:actor.id,project_id:projectId,event_name:"member_added",category:"projects",entity_type:"profile",entity_id:userId,metadata:{role:roleName}});}revalidatePath("/admin/users");revalidatePath("/admin/projects");}

export async function removeManagedMember(fd:FormData){const actor=await requireControlRoomAdmin();const admin=createAdminClient();const memberId=read(fd,"member_id");const {data:member}=await admin.from("project_members").select("id,project_id,user_id").eq("id",memberId).single();if(!member)throw new Error("Membership not found.");await admin.from("project_members").update({status:"removed"}).eq("id",memberId);await admin.from("platform_events").insert({user_id:actor.id,project_id:member.project_id,event_name:"member_removed",category:"admin",entity_type:"profile",entity_id:member.user_id});revalidatePath("/admin/users");revalidatePath("/admin/projects");}

export async function restoreManagedMember(fd:FormData){const actor=await requireControlRoomAdmin();const admin=createAdminClient();const memberId=read(fd,"member_id");const {data:member}=await admin.from("project_members").select("id,project_id,user_id,status").eq("id",memberId).single();if(!member)throw new Error("Membership not found.");const {error}=await admin.from("project_members").update({status:"active"}).eq("id",memberId);if(error)throw new Error(error.message);await admin.from("notifications").insert({user_id:member.user_id,project_id:member.project_id,type:"project_access_restored",title:"Your project access was restored",body:"You can enter this project again with your existing role."});await admin.from("platform_events").insert({user_id:actor.id,project_id:member.project_id,event_name:"member_restored",category:"admin",entity_type:"profile",entity_id:member.user_id});revalidatePath("/admin/users");revalidatePath(`/admin/users/${member.user_id}`);revalidatePath("/admin/projects");}

export async function updateEnquiryStatus(fd:FormData){const actor=await requireControlRoomAdmin();const admin=createAdminClient();const enquiryId=read(fd,"enquiry_id");const status=read(fd,"status");if(!["new","reviewing","responded","closed"].includes(status))throw new Error("Choose a valid enquiry status.");const {error}=await admin.from("public_enquiries").update({status,updated_at:new Date().toISOString()}).eq("id",enquiryId);if(error)throw new Error(error.message);await admin.from("platform_events").insert({user_id:actor.id,event_name:"enquiry_status_updated",category:"enquiries",entity_type:"public_enquiry",entity_id:enquiryId,metadata:{status}});revalidatePath("/admin/enquiries");}
