"use server";

import {revalidatePath} from "next/cache";
import {requireControlRoomAdmin} from "../../../lib/controlRoom";
import {createAdminClient} from "../../../lib/supabase/admin";
import {assertR2BucketAccess,assertR2ObjectAccess,createR2PresignedUrl,isR2Configured} from "../../../lib/r2";

const read=(fd:FormData,key:string)=>String(fd.get(key)||"").trim();

export async function updateManagedProject(fd:FormData){const user=await requireControlRoomAdmin();const admin=createAdminClient();const projectId=read(fd,"project_id");const status=read(fd,"status");const capacity=Number(read(fd,"default_beat_capacity"));if(!["active","paused","completed","archived"].includes(status))throw new Error("Invalid project status.");if(!Number.isInteger(capacity)||capacity<1||capacity>12)throw new Error("Artist capacity must be between 1 and 12.");const {error}=await admin.from("projects").update({status,default_beat_capacity:capacity,updated_at:new Date().toISOString()}).eq("id",projectId);if(error)throw new Error(error.message);await admin.from("platform_events").insert({user_id:user.id,project_id:projectId,event_name:"project_settings_updated",category:"admin",entity_type:"project",entity_id:projectId});revalidatePath("/admin/projects");revalidatePath("/admin");}

export async function updateSystemSetting(fd:FormData){const user=await requireControlRoomAdmin();const admin=createAdminClient();const key=read(fd,"setting_key");const raw=read(fd,"setting_value");let value:any;try{value=JSON.parse(raw)}catch{throw new Error("Setting value must be valid JSON.")}const {error}=await admin.from("system_settings").upsert({setting_key:key,setting_value:value,updated_by:user.id,updated_at:new Date().toISOString()},{onConflict:"setting_key"});if(error)throw new Error(error.message);await admin.from("platform_events").insert({user_id:user.id,event_name:"system_setting_updated",category:"admin",metadata:{setting_key:key}});revalidatePath("/admin/system");}

export async function addUsersToManagedProject(fd:FormData){const actor=await requireControlRoomAdmin();const admin=createAdminClient();const projectId=read(fd,"project_id");const roleName=read(fd,"role_name");const userIds=fd.getAll("user_ids").map(String).filter(Boolean);if(!userIds.length)throw new Error("Select at least one user.");const {data:role}=await admin.from("roles").select("id").eq("name",roleName).maybeSingle();if(!role)throw new Error("Choose a valid project role.");for(const userId of userIds){const {data:existing}=await admin.from("project_members").select("id,status").eq("project_id",projectId).eq("user_id",userId).maybeSingle();let memberId=existing?.id;if(memberId)await admin.from("project_members").update({status:"active"}).eq("id",memberId);else{const created=await admin.from("project_members").insert({project_id:projectId,user_id:userId,status:"active"}).select("id").single();if(created.error)throw new Error(created.error.message);memberId=created.data.id;}await admin.from("member_roles").upsert({project_member_id:memberId,role_id:role.id},{onConflict:"project_member_id,role_id"});await admin.from("notifications").insert({user_id:userId,project_id:projectId,type:"project_added",title:"You were added to a project",body:`You now have ${roleName} access.`});await admin.from("platform_events").insert({user_id:actor.id,project_id:projectId,event_name:"member_added",category:"projects",entity_type:"profile",entity_id:userId,metadata:{role:roleName}});}revalidatePath("/admin/users");revalidatePath("/admin/projects");}

export async function removeManagedMember(fd:FormData){const actor=await requireControlRoomAdmin();const admin=createAdminClient();const memberId=read(fd,"member_id");const {data:member}=await admin.from("project_members").select("id,project_id,user_id").eq("id",memberId).single();if(!member)throw new Error("Membership not found.");await admin.from("project_members").update({status:"removed"}).eq("id",memberId);await admin.from("platform_events").insert({user_id:actor.id,project_id:member.project_id,event_name:"member_removed",category:"admin",entity_type:"profile",entity_id:member.user_id});revalidatePath("/admin/users");revalidatePath("/admin/projects");}

export async function restoreManagedMember(fd:FormData){const actor=await requireControlRoomAdmin();const admin=createAdminClient();const memberId=read(fd,"member_id");const {data:member}=await admin.from("project_members").select("id,project_id,user_id,status").eq("id",memberId).single();if(!member)throw new Error("Membership not found.");const {error}=await admin.from("project_members").update({status:"active"}).eq("id",memberId);if(error)throw new Error(error.message);await admin.from("notifications").insert({user_id:member.user_id,project_id:member.project_id,type:"project_access_restored",title:"Your project access was restored",body:"You can enter this project again with your existing role."});await admin.from("platform_events").insert({user_id:actor.id,project_id:member.project_id,event_name:"member_restored",category:"admin",entity_type:"profile",entity_id:member.user_id});revalidatePath("/admin/users");revalidatePath(`/admin/users/${member.user_id}`);revalidatePath("/admin/projects");}

const creatorTypeOptions=new Set(["Artist","Producer","Songwriter / Composer","Engineer / Technical","Manager","Videographer / Photographer","Designer / Visual Creative","Content / Media","Session Musician","Other Creative"]);
export async function updateManagedCreatorProfile(fd:FormData){const actor=await requireControlRoomAdmin();const admin=createAdminClient();const userId=read(fd,"user_id");const creatorTypes=fd.getAll("creator_types").map(String).filter(type=>creatorTypeOptions.has(type));const songs=Array.from({length:5},(_,index)=>({title:read(fd,`song_${index+1}_title`),url:read(fd,`song_${index+1}_url`)})).filter(song=>song.title);const update={full_name:read(fd,"full_name"),stage_name:read(fd,"stage_name")||null,nickname:read(fd,"nickname")||null,bio:read(fd,"bio")||null,location:read(fd,"location")||null,creator_types:creatorTypes,social_links:read(fd,"social_url")?{primary:read(fd,"social_url")}:{},streaming_links:read(fd,"streaming_url")?{primary:read(fd,"streaming_url")}:{},top_songs:songs,updated_at:new Date().toISOString()};if(!update.full_name)throw new Error("Full name is required.");const{error}=await admin.from("profiles").update(update).eq("id",userId);if(error)throw new Error(error.message);await admin.from("platform_events").insert({user_id:actor.id,event_name:"creator_profile_updated",category:"admin",entity_type:"profile",entity_id:userId});revalidatePath("/admin/users");revalidatePath(`/admin/users/${userId}`);revalidatePath("/people");revalidatePath("/workspace");}

export async function updateEnquiryStatus(fd:FormData){const actor=await requireControlRoomAdmin();const admin=createAdminClient();const enquiryId=read(fd,"enquiry_id");const status=read(fd,"status");if(!["new","reviewing","responded","closed"].includes(status))throw new Error("Choose a valid enquiry status.");const {error}=await admin.from("public_enquiries").update({status,updated_at:new Date().toISOString()}).eq("id",enquiryId);if(error)throw new Error(error.message);await admin.from("platform_events").insert({user_id:actor.id,event_name:"enquiry_status_updated",category:"enquiries",entity_type:"public_enquiry",entity_id:enquiryId,metadata:{status}});revalidatePath("/admin/enquiries");}

const musicCreditRoles=new Set(["artist","featured_artist","producer","co_producer","songwriter","composer","engineer","mix_engineer","mastering_engineer","vocalist","instrumentalist","a&r","manager","visual_creative","other"]);

async function managedMusicRecord(entityType:string,entityId:string){const admin=createAdminClient();if(!["beat","track"].includes(entityType))throw new Error("Choose a valid music record.");const table=entityType==="beat"?"beats":"tracks";const {data,error}=await admin.from(table).select("id,project_id").eq("id",entityId).maybeSingle();if(error)throw new Error(error.message);if(!data)throw new Error("That music record no longer exists.");return{admin,record:data,table};}

function refreshMusicCatalog(){revalidatePath("/admin/operations");revalidatePath("/beats");revalidatePath("/tracks");revalidatePath("/workspace");}

export async function prepareAdminArtworkUpload(fd:FormData){await requireControlRoomAdmin();const entityType=read(fd,"entity_type");const entityId=read(fd,"entity_id");const fileName=read(fd,"file_name");const mimeType=read(fd,"file_type");const fileSize=Number(read(fd,"file_size"));const{record}=await managedMusicRecord(entityType,entityId);if(!isR2Configured())throw new Error("Cloudflare R2 is not configured.");if(!fileName||!mimeType.startsWith("image/")||!Number.isFinite(fileSize)||fileSize<=0)throw new Error("Choose a valid JPG, PNG or WebP image.");if(fileSize>12*1024*1024)throw new Error("Artwork must be smaller than 12 MB.");await assertR2BucketAccess();const safe=fileName.replace(/[^a-zA-Z0-9._-]/g,"-");const storageKey=`${record.project_id}/artwork/${entityType}s/${entityId}/${crypto.randomUUID()}-${safe}`;return{storageKey,uploadUrl:await createR2PresignedUrl("PUT",storageKey,900,mimeType)};}

export async function saveAdminArtwork(fd:FormData){const actor=await requireControlRoomAdmin();const entityType=read(fd,"entity_type");const entityId=read(fd,"entity_id");const storageKey=read(fd,"storage_key");if(!storageKey)throw new Error("The artwork transfer is incomplete.");const{admin,record,table}=await managedMusicRecord(entityType,entityId);await assertR2ObjectAccess(storageKey);const{error}=await admin.from(table).update({artwork_storage_key:storageKey,artwork_url:null,updated_at:new Date().toISOString()}).eq("id",entityId);if(error)throw new Error(error.message);await admin.from("platform_events").insert({user_id:actor.id,project_id:record.project_id,event_name:`${entityType}_artwork_updated`,category:"admin",entity_type:entityType,entity_id:entityId});refreshMusicCatalog();return{message:"Thumbnail updated."};}

export async function replaceAdminMusicCredits(fd:FormData){const actor=await requireControlRoomAdmin();const entityType=read(fd,"entity_type");const entityId=read(fd,"entity_id");const{admin,record}=await managedMusicRecord(entityType,entityId);const ids=fd.getAll("credit_user_id").map(String);const roles=fd.getAll("credit_role").map(String);const credits=ids.map((userId,index)=>({user_id:userId.trim(),contribution_role:(roles[index]||"other").trim().toLowerCase()})).filter(item=>item.user_id&&musicCreditRoles.has(item.contribution_role));const unique=Array.from(new Map(credits.map(item=>[`${item.user_id}:${item.contribution_role}`,item])).values());if(unique.length){const{data:members,error:membersError}=await admin.from("project_members").select("user_id").eq("project_id",record.project_id).eq("status","active").in("user_id",Array.from(new Set(unique.map(item=>item.user_id))));if(membersError)throw new Error(membersError.message);const active=new Set((members||[]).map(item=>item.user_id));if(unique.some(item=>!active.has(item.user_id)))throw new Error("Every credited person must be an active project member.");}const table=entityType==="beat"?"beat_contributors":"track_contributors";const foreignKey=entityType==="beat"?"beat_id":"track_id";const{error:deleteError}=await admin.from(table).delete().eq(foreignKey,entityId);if(deleteError)throw new Error(deleteError.message);if(unique.length){const{error:insertError}=await admin.from(table).insert(unique.map(item=>({[foreignKey]:entityId,user_id:item.user_id,contribution_role:item.contribution_role,approved:true})));if(insertError)throw new Error(insertError.message);}await admin.from("platform_events").insert({user_id:actor.id,project_id:record.project_id,event_name:`${entityType}_credits_replaced`,category:"admin",entity_type:entityType,entity_id:entityId,metadata:{credit_count:unique.length}});refreshMusicCatalog();return{message:"Credits updated."};}

export async function deleteAdminMusicRecord(fd:FormData){const actor=await requireControlRoomAdmin();const entityType=read(fd,"entity_type");const entityId=read(fd,"entity_id");if(read(fd,"confirmation")!=="DELETE")throw new Error("Deletion was not confirmed.");const{admin,record,table}=await managedMusicRecord(entityType,entityId);if(entityType==="beat"){const{data:linkedTrack}=await admin.from("tracks").select("id").eq("beat_id",entityId).limit(1).maybeSingle();if(linkedTrack)throw new Error("This beat is linked to a track. Delete that track first.");await Promise.all([admin.from("comments").delete().eq("entity_type","beat").eq("entity_id",entityId),admin.from("beat_claims").delete().eq("beat_id",entityId),admin.from("beat_interest").delete().eq("beat_id",entityId),admin.from("beat_assignments").delete().eq("beat_id",entityId),admin.from("beat_contributors").delete().eq("beat_id",entityId)]);}else{await Promise.all([admin.from("comments").delete().eq("entity_type","track").eq("entity_id",entityId),admin.from("project_assets").delete().eq("entity_type","track").eq("entity_id",entityId)]);}const{error}=await admin.from(table).delete().eq("id",entityId);if(error)throw new Error(error.message);await admin.from("platform_events").insert({user_id:actor.id,project_id:record.project_id,event_name:`${entityType}_deleted`,category:"admin",metadata:{deleted_entity_id:entityId}});refreshMusicCatalog();return{message:`${entityType==="beat"?"Beat":"Track"} deleted.`};}
