import AppShell from "../../components/AppShell";
import { getWorkspace } from "../../lib/workspace";
import { cancelJoinRequest, createProject, requestToJoin, selectProject } from "./actions";

export default async function ProjectsPage() {
  const { user, admin, activeProjects } = await getWorkspace();
  const [{ data: projects = [] }, { data: requests = [] }] = await Promise.all([
    admin.from("projects").select("id,code,name,description,status,artwork_url,join_requests_open,created_at").eq("visibility", "discoverable").order("created_at", { ascending: false }),
    admin.from("project_join_requests").select("id,project_id,status,created_at").eq("user_id", user.id).order("created_at", { ascending: false }),
  ]);
  const requestMap = new Map((requests || []).map((r: any) => [r.project_id, r]));
  const memberIds = new Set((activeProjects || []).map((p: any) => p.id));
  return <AppShell><div className="content project-hub-page">
    <div className="heading"><div><span className="eyebrow">YOUR CREATIVE WORLD</span><h1>Projects</h1><p>Enter a project you belong to, discover an open room, or begin one of your own.</p></div></div>
    {!!activeProjects.length && <section className="project-hub-section"><h2>My projects</h2><div className="project-card-grid">{activeProjects.map((project:any)=><article className="panel project-discovery-card" key={project.id}><span className="eyebrow">{project.code}</span><h2>{project.name}</h2><p>{project.description || "A FACKTS Music creative project."}</p><form action={selectProject}><input type="hidden" name="project_id" value={project.id}/><button className="login-submit-btn">Enter project</button></form></article>)}</div></section>}
    <section className="project-hub-section"><h2>Explore projects</h2><div className="project-card-grid">{!(projects || []).length && <div className="panel empty-state"><h2>No open projects yet</h2><p>Discoverable projects will appear here when their team opens requests.</p></div>}{(projects || []).map((project:any)=>{const request:any=requestMap.get(project.id);return <article className="panel project-discovery-card" key={project.id}>{project.artwork_url&&<img src={project.artwork_url} alt=""/>}<span className="eyebrow">{project.status} · {project.join_requests_open?"REQUESTS OPEN":"VIEW ONLY"}</span><h2>{project.name}</h2><p>{project.description || "A FACKTS Music creative project."}</p>{memberIds.has(project.id)?<form action={selectProject}><input type="hidden" name="project_id" value={project.id}/><button>Enter project</button></form>:request?.status==="pending"?<div className="join-request-status"><strong>Request pending</strong><form action={cancelJoinRequest}><input type="hidden" name="request_id" value={request.id}/><button>Cancel request</button></form></div>:project.join_requests_open?<form action={requestToJoin} className="project-request-form"><input type="hidden" name="project_id" value={project.id}/><textarea name="message" placeholder="A short note to the project team (optional)"/><button>Request to Join</button></form>:<span className="status-pill">Requests closed</span>}</article>})}</div></section>
    <section className="panel create-project-panel"><span className="eyebrow">START A ROOM</span><h2>Create a project</h2><p>You will become its Project Lead. Nothing is added to Project 001.</p><form action={createProject} className="operations-form"><input name="name" required placeholder="Project name"/><textarea name="description" placeholder="What are you building?"/><select name="visibility" defaultValue="private"><option value="private">Private project</option><option value="discoverable">Discoverable project</option></select><label className="terms-check"><input type="checkbox" name="join_requests_open"/>Allow join requests</label><button>Create project</button></form></section>
  </div></AppShell>;
}
