import Sidebar from "../components/Sidebar";import Topbar from "../components/Topbar";import {metrics,actions,pipeline,activity} from "../lib/data";
const slug=(s:string)=>s.toLowerCase().replaceAll(" ","-");
export default function Home(){return <main className="shell"><Sidebar/><section className="main"><Topbar/><div className="content">
<div className="heading enter"><div><span className="eyebrow">KREYO / PROJECT 001</span><h1>Good evening, Joseph.</h1><p>Here’s what needs attention across the founding music venture.</p></div><span className="date">18 AUG 2026</span></div>
<section className="progress enter d1"><div className="progress-head"><div><span>PROJECT HEALTH</span><b>38% complete</b></div><em>Production</em></div><div className="track"><i/></div><div className="legend"><span>Setup</span><span>Writing</span><span className="now">Production</span><span>Rights</span><span>Release ready</span></div></section>
<section className="metrics enter d2">{metrics.map(m=><article className="metric" key={m.label}><span>{m.label}</span><div><b>{m.value}</b><small className={m.warn?"warn":""}>{m.note}</small></div></article>)}</section>
<section className="grid enter d3"><article className="panel"><header><div><span className="eyebrow">MY WORK</span><h2>Actions requiring attention</h2></div><button>View all ↗</button></header><div>{actions.map((a,i)=><div className="action" key={a[0]}><span>{String(i+1).padStart(2,"0")}</span><div><b>{a[0]}</b><small>{a[1]}</small></div><em>{a[2]}</em><strong className={slug(a[3])}>{a[3]}</strong></div>)}</div></article>
<article className="panel"><header><div><span className="eyebrow">PROJECT FLOW</span><h2>Current pipeline</h2></div></header>{pipeline.map(p=><div className="pipe" key={p[0]}><div><b>{p[0]}</b><small>{p[1]}</small></div><div><b><i className={slug(p[2])}/>{p[2]}</b><small>{p[3]}</small></div></div>)}</article></section>
<section className="grid lower enter d4"><article className="panel"><header><div><span className="eyebrow">OPERATING HISTORY</span><h2>Recent activity</h2></div><button>Full activity ↗</button></header>{activity.map((a,i)=><div className="activity" key={a[1]}><span><i/>{i<activity.length-1&&<b/>}</span><div><p><strong>{a[0]}</strong> {a[1]}</p><small>{a[2]}</small></div></div>)}</article>
<article className="panel economics"><header><div><span className="eyebrow">PROJECT ECONOMICS</span><h2>Recoupment</h2></div></header><div className="money">KES 0</div><p>Revenue recorded</p><div className="econrows"><div><span>Project spend</span><b>KES —</b></div><div><span>Still to recoup</span><b>KES —</b></div><div><span>Net surplus</span><b>KES —</b></div></div><button className="secondary">Open finance workspace</button></article></section>
</div></section></main>}