export const MUSIC_HELP = [
  { title: "Find my projects", keywords: "project join invitation invite access missing", answer: "Open My Projects to see your projects and invitations. Accept an invitation, then enter the project. If a project is missing, ask its lead to invite the email address you use to sign in.", href: "/projects" },
  { title: "Review my splits", keywords: "split share percentage approve confirm ownership", answer: "Open My pending approvals, choose a song and review the complete proposal. Confirm your own share if it is correct, or request a change. Management saves the allocations and sends the 100% proposal. Any revision resets all approvals.", href: "/splits?view=mine" },
  { title: "Open music and files", keywords: "song music audio file upload track beat version", answer: "Enter your project and open Music. Choose a song title to open its details, credits, files and rights status. Use Audio & versions for listening and track work. Upload controls depend on your role in the selected project.", href: "/tracks", project: true },
  { title: "Understand credits", keywords: "credit record writer producer engineer contribution", answer: "Credits describe who contributed and what they did. A credit does not automatically assign a percentage. Open the song details for its credits, or My credits under More for your professional record.", href: "/professional-record" },
  { title: "Find my next task", keywords: "task todo assignment action deadline work", answer: "Open My open tasks to see assignments across your active projects. Opening an item selects its project. Splits awaiting your confirmation are listed separately on Home.", href: "/my-actions?kind=tasks" },
  { title: "Check studio sessions", keywords: "studio session booking record recording schedule", answer: "Open Upcoming project sessions to see scheduled sessions across your projects. Open a session's project to review the booking and details.", href: "/my-actions?kind=sessions" },
  { title: "Read my messages", keywords: "inbox notification alert message request", answer: "Open Inbox for invitations, updates and approval requests. Open takes you to the relevant project and page. Marking a message as read does not approve a split.", href: "/inbox" },
  { title: "Update my profile", keywords: "profile account photo name password settings", answer: "Open My Profile to update your account and creator details. If you cannot sign in, use Forgot password on the sign-in page.", href: "/settings" },
] as const;
export function guideAnswer(question: string) {
  const words=question.toLowerCase().match(/[a-z]+/g)||[];
  const ranked=MUSIC_HELP.map(topic=>({topic,score:words.filter(word=>word.length>2&&`${topic.title} ${topic.keywords}`.toLowerCase().includes(word)).length})).sort((a,b)=>b.score-a.score);
  return ranked[0]?.score ? {answer:ranked[0].topic.answer,links:ranked.filter(item=>item.score>0).slice(0,3).map(item=>({title:item.topic.title,href:item.topic.href}))} : {answer:"I can help you find projects, songs, split approvals, credits, sessions and tasks. Choose a topic or ask where you want to go.",links:MUSIC_HELP.slice(0,3).map(topic=>({title:topic.title,href:topic.href}))};
}
