import type { Metadata } from "next";
import PublicNavigation from "../../components/PublicNavigation";
import PublicFooter from "../../components/PublicFooter";
import { submitPartnership } from "./actions";

export const metadata: Metadata = { title:"Partner With Us",description:"Partner with FACKTS Music to build better creative infrastructure.",alternates:{canonical:"/partner"} };

const partners=["Studios & creative spaces","Labels & artist collectives","Brands & agencies","Media & cultural organisations","Technology & distribution partners","Funders & development partners"];
export default async function PartnerPage({searchParams}:{searchParams:Promise<{success?:string;error?:string}>}){const notice=await searchParams;return <main className="public-site"><PublicNavigation/><header className="public-page-hero partner"><span className="public-eyebrow">PARTNER WITH FACKTS MUSIC</span><h1>Build the room.<br/><em>Move the music.</em></h1><p>We work with organisations that believe African creative work deserves stronger infrastructure, clearer records and better pathways to market.</p></header><section className="public-story-grid"><div><span className="public-eyebrow">WHO WE BUILD WITH</span><h2>Different strengths.<br/>One creative future.</h2></div><div className="public-partner-list">{partners.map((item,index)=><article key={item}><span>{String(index+1).padStart(2,"0")}</span><h3>{item}</h3></article>)}</div></section><section className="public-form-layout partner-form-layout"><div className="public-contact-card"><span className="public-eyebrow">WHY PARTNER</span><h2>Turn shared ambition into practical movement.</h2><p>Partnerships may support creator development, studio programmes, technology integrations, project funding, content, research or new routes to opportunity.</p><p>Tell us what you are building and where FACKTS Music could create real value with you.</p></div><form action={submitPartnership} className="public-enquiry-form"><div className="public-form-heading"><span>START A CONVERSATION</span><h2>Partnership proposal.</h2></div>{notice.success&&<p className="public-form-notice success">{notice.success}</p>}{notice.error&&<p className="public-form-notice error">{notice.error}</p>}<label>Name *<input name="name" required autoComplete="name"/></label><label>Organisation *<input name="organisation" required autoComplete="organization"/></label><label>Email *<input name="email" type="email" required autoComplete="email"/></label><label>Phone<input name="phone" type="tel" autoComplete="tel"/></label><label className="public-form-wide">Partnership type *<select name="partnership_type" required defaultValue=""><option value="" disabled>Select one</option>{partners.map(item=><option key={item}>{item}</option>)}</select></label><label className="public-form-wide">What would you like to build together? *<textarea name="message" required minLength={20} rows={7}/></label><button className="public-button public-button-primary public-form-wide" type="submit">Send Proposal →</button></form></section><PublicFooter/></main>}
