import AppShell from "../../components/AppShell";
import { getWorkspace } from "../../lib/workspace";
import { submitSuggestion } from "./actions";

export default async function SuggestionsPage({ searchParams }: { searchParams: Promise<{ submitted?: string }> }) {
  const params = await searchParams; const { user, admin, activeProjects } = await getWorkspace();
  const { data: items = [] } = await admin.from("platform_suggestions").select("id,suggestion_type,suggestion,status,created_at,projects(name)").eq("submitted_by", user.id).order("created_at", { ascending: false }).limit(15);
  return <AppShell><div className="content suggestions-page"><section className="discover-hero"><span className="eyebrow">SUGGEST SOMETHING</span><h1>Help the system learn from the room.</h1><p>Share an improvement, project idea, music note or problem. Your submission stays connected to the right context and reaches the operating team.</p></section>{params.submitted && <div className="form-success-alert">Suggestion received. Thank you.</div>}<section className="platform-home-split"><article className="platform-home-section"><div className="platform-section-heading"><div><span className="eyebrow">NEW SUGGESTION</span><h2>What should move?</h2></div></div><form action={submitSuggestion} className="operations-form"><label>Suggestion type<select name="suggestion_type" defaultValue="platform_improvement"><option value="platform_improvement">Platform Improvement</option><option value="project_idea">Project Idea</option><option value="track_project_feedback">Track / Project Feedback</option><option value="bug_problem">Bug / Problem</option><option value="other">Other</option></select></label><label>Project<select name="project_id" defaultValue=""><option value="">Platform-wide</option>{activeProjects.map((project: any)=><option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label className="full">Suggestion<textarea name="suggestion" required placeholder="Describe the idea or problem clearly…"/></label><button>Submit suggestion</button></form></article><article className="platform-home-section"><div className="platform-section-heading"><div><span className="eyebrow">YOUR SUBMISSIONS</span><h2>Status</h2></div></div><div className="home-list">{!items?.length&&<p className="home-empty-copy">No suggestions submitted yet.</p>}{(items||[]).map((item:any)=><div key={item.id}><time>{new Date(item.created_at).toLocaleDateString("en-KE")}</time><span><strong>{item.suggestion_type.replaceAll("_"," ")}</strong><small>{item.suggestion} · {item.status.replaceAll("_"," ")}</small></span></div>)}</div></article></section></div></AppShell>;
}
