import { notFound } from "next/navigation";
import { createAdminClient } from "../../../../../lib/supabase/admin";
import { updateManagedProject } from "../../actions";

const first = (value: any) => Array.isArray(value) ? value[0] : value;
export default async function AdminProjectOverview({ params }: { params: Promise<{ projectId: string }> }) {
  const { projectId } = await params;
  const admin = createAdminClient();
  const [{ data: project }, { data: events = [] }] = await Promise.all([
    admin.from("projects").select("*,project_members(id,status,profiles(id,full_name,stage_name,email),member_roles(roles(name))),beats(id,status),tracks(id,status),studio_sessions(id,status),project_tasks(id,status)").eq("id", projectId).maybeSingle(),
    admin.from("platform_events").select("id,event_name,category,created_at,profiles(full_name,stage_name)").eq("project_id", projectId).order("created_at", { ascending: false }).limit(20),
  ]);
  if (!events) throw new Error("Control Room project activity could not be loaded.");
  if (!project) notFound();
  const members = (project.project_members || []).filter((member: any) => member.status === "active");
  return <><section className="control-page-hero projects"><span className="control-eyebrow">ADMIN PROJECT OVERVIEW</span><h1>{project.name}</h1><p>{project.description || "The system-level operating view for this project."}</p></section><section className="control-metrics"><article><span>Members</span><strong>{members.length}</strong><small>Active access</small></article><article><span>Beats</span><strong>{project.beats?.length || 0}</strong><small>Library records</small></article><article><span>Tracks</span><strong>{project.tracks?.length || 0}</strong><small>Development records</small></article><article><span>Open actions</span><strong>{(project.project_tasks || []).filter((task: any) => task.status !== "done").length}</strong><small>Outstanding</small></article><article><span>Sessions</span><strong>{project.studio_sessions?.length || 0}</strong><small>All session records</small></article><article><span>Progress</span><strong>{project.progress || 0}%</strong><small>{project.status}</small></article></section><section className="control-grid"><article className="control-panel"><header><div><span className="control-eyebrow">MEMBERS</span><h2>Project access</h2></div></header>{members.map((member: any) => { const profile = first(member.profiles); return <div className="control-row" key={member.id}><div><strong>{profile?.stage_name || profile?.full_name || profile?.email}</strong><small>{(member.member_roles || []).map((item: any) => first(item.roles)?.name).filter(Boolean).join(", ")}</small></div></div>; })}</article><article className="control-panel"><header><div><span className="control-eyebrow">CORE RULES</span><h2>Project settings</h2></div></header><form action={updateManagedProject} className="control-profile-add"><input type="hidden" name="project_id" value={project.id} /><label>Status<select name="status" defaultValue={project.status}><option>active</option><option>paused</option><option>completed</option><option>archived</option></select></label><label>Default artist slots<input type="number" name="default_beat_capacity" min="1" max="12" defaultValue={project.default_beat_capacity || 3} /></label><button>Save Project Settings</button></form></article></section><section className="control-panel control-activity"><header><div><span className="control-eyebrow">PROJECT ACTIVITY</span><h2>Recent movement</h2></div></header><div className="control-event-feed">{!events.length && <p className="control-empty">No project events recorded yet.</p>}{events.map((event: any) => { const profile = first(event.profiles); return <article key={event.id}><span className="control-activity-dot" /><div><strong>{event.event_name.replaceAll("_", " ")}</strong><p>{profile?.stage_name || profile?.full_name || "System"} · {event.category}</p></div><time>{new Date(event.created_at).toLocaleString("en-KE")}</time></article>; })}</div></section></>;
}
