-- FACKTS Music image storage. Audio remains in Cloudflare R2.
-- Existing profile buckets are already handled by earlier migrations.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'music-images',
  'music-images',
  false,
  12582912,
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Upload and playback use short-lived signed URLs generated by trusted server
-- actions. No public object policy is created for this bucket.
